#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Oct 19 17:17:24 CDT 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto eb18a95509d54f8eb4512571ac9c1320 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TB_Signal_Tap_Logic_behav xil_defaultlib.TB_Signal_Tap_Logic xil_defaultlib.glbl -log elaborate.log"
xelab -wto eb18a95509d54f8eb4512571ac9c1320 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TB_Signal_Tap_Logic_behav xil_defaultlib.TB_Signal_Tap_Logic xil_defaultlib.glbl -log elaborate.log

