webtalk_init -webtalk_dir /home/cameron/zschool/SeniorDesign/PCM_Serializer_2Channel/PCM_Serializer_2Channel.sim/sim_1/behav/xsim/xsim.dir/Serializer_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 10 15:34:04 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3d9a31c9ea015d28bf78aa86a2bfac85" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1752768ce86543b59e779ec629a7b9d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1580.582 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "7" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "177 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "11 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "225" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "311800_KB" -context "xsim\\usage"
webtalk_transmit -clientid 853114144 -regid "" -xml /home/cameron/zschool/SeniorDesign/PCM_Serializer_2Channel/PCM_Serializer_2Channel.sim/sim_1/behav/xsim/xsim.dir/Serializer_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cameron/zschool/SeniorDesign/PCM_Serializer_2Channel/PCM_Serializer_2Channel.sim/sim_1/behav/xsim/xsim.dir/Serializer_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cameron/zschool/SeniorDesign/PCM_Serializer_2Channel/PCM_Serializer_2Channel.sim/sim_1/behav/xsim/xsim.dir/Serializer_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
