# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_processing_system7_0_0/Zynq_I2C_CODEC_processing_system7_0_0.xci
# IP: The module: 'Zynq_I2C_CODEC_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_processing_system7_0_0/Zynq_I2C_CODEC_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_I2C_CODEC_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_processing_system7_0_0/Zynq_I2C_CODEC_processing_system7_0_0.xci
# IP: The module: 'Zynq_I2C_CODEC_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_processing_system7_0_0/Zynq_I2C_CODEC_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_I2C_CODEC_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
