# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/DAC_Array_Tester.xdc

# Block Designs: bd/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Base_Phased_Array || ORIG_REF_NAME==Zynq_Base_Phased_Array} -quiet] -quiet

# IP: bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_processing_system7_0_0/Zynq_Base_Phased_Array_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Base_Phased_Array_processing_system7_0_0 || ORIG_REF_NAME==Zynq_Base_Phased_Array_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_axi_iic_0_0/Zynq_Base_Phased_Array_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Base_Phased_Array_axi_iic_0_0 || ORIG_REF_NAME==Zynq_Base_Phased_Array_axi_iic_0_0} -quiet] -quiet

# IP: bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_ps7_0_axi_periph_0/Zynq_Base_Phased_Array_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Base_Phased_Array_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_Base_Phased_Array_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_rst_ps7_0_50M_0/Zynq_Base_Phased_Array_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Base_Phased_Array_rst_ps7_0_50M_0 || ORIG_REF_NAME==Zynq_Base_Phased_Array_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_auto_pc_0/Zynq_Base_Phased_Array_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Base_Phased_Array_auto_pc_0 || ORIG_REF_NAME==Zynq_Base_Phased_Array_auto_pc_0} -quiet] -quiet

# XDC: bd/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array_ooc.xdc
