# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.cache/wt [current_project]
set_property parent.project_path /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2
  /home/cameron/Digilent
} [current_project]
set_property ip_output_repo /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/cameron/PhaseArraySpeaker/Test_Signals/COE_File_Gen/coe/Sine_1k_24bit.coe
add_files /home/cameron/PhaseArraySpeaker/Test_Signals/COE_File_Gen/coe/Saw_1k_24bit.coe
add_files /home/cameron/PhaseArraySpeaker/Test_Signals/COE_File_Gen/coe/Dirac_1k_24bit.coe
add_files /home/cameron/PhaseArraySpeaker/Test_Signals/COE_File_Gen/coe/Triangle_1k_24bit.coe
read_verilog -library xil_defaultlib {
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/Address_Counter.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/sources_1/imports/sources_1/new/DAC_Array_Tester.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/Demux_RAM_Parallel_Output.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/FIFO_Latch_Clock.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/I2S_Latch_Pulse.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/I2S_Rx.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/PCM_Transmitter_16.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/Parallel_Signal_Tap.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/SR_Clock_Div_256.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/SR_Clock_Div_4.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/Serial_Clock_Divider.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/Serial_FIFO.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/Sigal_Buffer.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/new/Signal_Tap_Logic.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/sources_1/new/Up_Down_Counter.v
  /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/imports/hdl/Zynq_Base_Phased_Array_wrapper.v
}
add_files /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.bd
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_processing_system7_0_0/Zynq_Base_Phased_Array_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_axi_iic_0_0/Zynq_Base_Phased_Array_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_axi_iic_0_0/Zynq_Base_Phased_Array_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_rst_ps7_0_50M_0/Zynq_Base_Phased_Array_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_rst_ps7_0_50M_0/Zynq_Base_Phased_Array_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_rst_ps7_0_50M_0/Zynq_Base_Phased_Array_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/ip/Zynq_Base_Phased_Array_auto_pc_0/Zynq_Base_Phased_Array_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/sources_1/bd/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array_ooc.xdc]

read_ip -quiet /opt/Xilinx/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /opt/Xilinx/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /opt/Xilinx/Sine_ROM/Sine_ROM.xci
set_property used_in_implementation false [get_files -all /opt/Xilinx/Sine_ROM/Sine_ROM_ooc.xdc]

read_ip -quiet /opt/Xilinx/Saw_ROM/Saw_ROM.xci
set_property used_in_implementation false [get_files -all /opt/Xilinx/Saw_ROM/Saw_ROM_ooc.xdc]

read_ip -quiet /opt/Xilinx/Triangle_ROM/Triangle_ROM.xci
set_property used_in_implementation false [get_files -all /opt/Xilinx/Triangle_ROM/Triangle_ROM_ooc.xdc]

read_ip -quiet /opt/Xilinx/Dirac_ROM/Dirac_ROM.xci
set_property used_in_implementation false [get_files -all /opt/Xilinx/Dirac_ROM/Dirac_ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/constrs_1/imports/new/DAC_Array_Tester.xdc
set_property used_in_implementation false [get_files /home/cameron/PhaseArraySpeaker/Firmware/2018.2/Zynq_Base_Phased_Array/Zynq_Base_Phased_Array.srcs/constrs_1/imports/new/DAC_Array_Tester.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Zynq_Base_Phased_Array_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Zynq_Base_Phased_Array_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Zynq_Base_Phased_Array_wrapper_utilization_synth.rpt -pb Zynq_Base_Phased_Array_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
