# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/ip/Saw_ROM/Saw_ROM.xci
# IP: The module: 'Saw_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/ip/Saw_ROM/Saw_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Saw_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/ip/Saw_ROM/Saw_ROM.xci
# IP: The module: 'Saw_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameron/PhaseArraySpeaker/Firmware/2017.2/Phase_Array_DSP_AUX/Phase_Array_DSP_AUX.srcs/sources_1/ip/Saw_ROM/Saw_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Saw_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
