#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Oct 16 15:10:08 CDT 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 9058eab0e22e46d1a8d0e81c5b5cfdfb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot Clock_Div_TB_behav xil_defaultlib.Clock_Div_TB xil_defaultlib.glbl -log elaborate.log"
xelab -wto 9058eab0e22e46d1a8d0e81c5b5cfdfb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot Clock_Div_TB_behav xil_defaultlib.Clock_Div_TB xil_defaultlib.glbl -log elaborate.log

