# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/DAC_Array_Tester.xdc

# Block Designs: bd/Zynq_I2C_CODEC/Zynq_I2C_CODEC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_I2C_CODEC || ORIG_REF_NAME==Zynq_I2C_CODEC}]

# IP: bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_processing_system7_0_0/Zynq_I2C_CODEC_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_I2C_CODEC_processing_system7_0_0 || ORIG_REF_NAME==Zynq_I2C_CODEC_processing_system7_0_0}]

# IP: bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_axi_iic_0_0/Zynq_I2C_CODEC_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_I2C_CODEC_axi_iic_0_0 || ORIG_REF_NAME==Zynq_I2C_CODEC_axi_iic_0_0}]

# IP: bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_ps7_0_axi_periph_0/Zynq_I2C_CODEC_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_I2C_CODEC_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_I2C_CODEC_ps7_0_axi_periph_0}]

# IP: bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_rst_ps7_0_50M_0/Zynq_I2C_CODEC_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_I2C_CODEC_rst_ps7_0_50M_0 || ORIG_REF_NAME==Zynq_I2C_CODEC_rst_ps7_0_50M_0}]

# IP: bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_xlconstant_0_0/Zynq_I2C_CODEC_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_I2C_CODEC_xlconstant_0_0 || ORIG_REF_NAME==Zynq_I2C_CODEC_xlconstant_0_0}]

# IP: bd/Zynq_I2C_CODEC/ip/Zynq_I2C_CODEC_auto_pc_0/Zynq_I2C_CODEC_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_I2C_CODEC_auto_pc_0 || ORIG_REF_NAME==Zynq_I2C_CODEC_auto_pc_0}]

# XDC: bd/Zynq_I2C_CODEC/Zynq_I2C_CODEC_ooc.xdc
