# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /opt/Xilinx/Dirac_ROM/Dirac_ROM.xci
# IP: The module: 'Dirac_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Dirac_ROM/Dirac_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dirac_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /opt/Xilinx/Dirac_ROM/Dirac_ROM.xci
# IP: The module: 'Dirac_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Dirac_ROM/Dirac_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dirac_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
