# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.cache/wt [current_project]
set_property parent.project_path /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.board [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.ipdefs/repo_0 [current_project]
set_property ip_output_repo /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/cameron/PhaseArraySpeaker/Test_Signals/COE_File_Gen/coe/Sine_1k_24bit.coe
read_verilog -library xil_defaultlib {
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/sources_1/imports/sources_1/imports/new/Address_Counter.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/sources_1/imports/sources_1/new/DAC_Array_Tester.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/Demux_RAM_Parallel_Output.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/I2S_Rx.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/PCM_Transmitter_16.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/Parallel_Signal_Tap.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/Serial_Clock_Divider.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/Serial_FIFO.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/Sigal_Buffer.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/imports/imports/new/Signal_Tap_Logic.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/new/TwoCycleHigh.v
  /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
read_ip -quiet /opt/Xilinx/Sine_ROM_2/Sine_ROM.xci
set_property used_in_implementation false [get_files -all /opt/Xilinx/Sine_ROM_2/Sine_ROM_ooc.xdc]

add_files /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_d_axi_i2s_audio_0_0/src/fifo_32/fifo_32.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_d_axi_i2s_audio_0_0/src/fifo_32/fifo_32_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_d_axi_i2s_audio_0_0/src/fifo_4/fifo_4.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_d_axi_i2s_audio_0_0/src/fifo_4/fifo_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_d_axi_i2s_audio_0_0/src/d_axi_i2s_audio.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/constrs_1/imports/constraints/zybo-z7-dma.xdc
set_property used_in_implementation false [get_files /home/cameron/PhaseArraySpeaker/Firmware/OTHER/Zybo-Z7-10-DMA-2018.2-1/vivado_proj/Zybo-Z7-10-DMA.srcs/constrs_1/imports/constraints/zybo-z7-dma.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top system_wrapper -part xc7z010clg400-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
