# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/DAC_Array_Tester.xdc

# IP: ip/PCM_Transmitter_16_0/PCM_Transmitter_16_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCM_Transmitter_16_0 || ORIG_REF_NAME==PCM_Transmitter_16_0} -quiet] -quiet

# IP: ip/Saw_ROM/Saw_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Saw_ROM || ORIG_REF_NAME==Saw_ROM} -quiet] -quiet

# IP: ip/Sine_ROM/Sine_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sine_ROM || ORIG_REF_NAME==Sine_ROM} -quiet] -quiet
