# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cameron/PhaseArraySpeaker/Firmware/DAC_Array_ROM_Tester/DAC_Array_ROM_Tester.srcs/sources_1/ip/Dirac_ROM/Dirac_ROM.xci
# IP: The module: 'Dirac_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameron/PhaseArraySpeaker/Firmware/DAC_Array_ROM_Tester/DAC_Array_ROM_Tester.gen/sources_1/ip/Dirac_ROM/Dirac_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dirac_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/cameron/PhaseArraySpeaker/Firmware/DAC_Array_ROM_Tester/DAC_Array_ROM_Tester.srcs/sources_1/ip/Dirac_ROM/Dirac_ROM.xci
# IP: The module: 'Dirac_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameron/PhaseArraySpeaker/Firmware/DAC_Array_ROM_Tester/DAC_Array_ROM_Tester.gen/sources_1/ip/Dirac_ROM/Dirac_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dirac_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
