#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Oct 16 15:34:13 CDT 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto e4e96e662c2d49438fd933be4ae47b25 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot PCM_Transmitter_16_behav xil_defaultlib.PCM_Transmitter_16 xil_defaultlib.glbl -log elaborate.log"
xelab -wto e4e96e662c2d49438fd933be4ae47b25 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot PCM_Transmitter_16_behav xil_defaultlib.PCM_Transmitter_16 xil_defaultlib.glbl -log elaborate.log

